# Generated by Django 4.2.6 on 2023-10-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glowny', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='kod_pocztowy',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='miasto',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nr_domu',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ulica',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='wojewodztwo',
            field=models.TextField(default='', max_length=50),
        ),
    ]
