# Generated by Django 4.2.6 on 2023-10-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glowny', '0002_customuser_kod_pocztowy_customuser_miasto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='kod_pocztowy',
            field=models.TextField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='miasto',
            field=models.TextField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nr_domu',
            field=models.TextField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='ulica',
            field=models.TextField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='wojewodztwo',
            field=models.TextField(default='', max_length=30),
        ),
    ]
