# Generated by Django 4.2.6 on 2023-10-25 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glowny', '0003_alter_customuser_kod_pocztowy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_staff',
            new_name='is_premium',
        ),
    ]
