# Generated by Django 4.2.6 on 2023-10-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glowny', '0005_customuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='kod_pocztowy',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='miasto',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nr_domu',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='ulica',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='wojewodztwo',
            field=models.CharField(default='', max_length=30),
        ),
    ]
