# Generated by Django 4.2.6 on 2023-10-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('przedmioty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='desciption',
            field=models.CharField(default='', max_length=255),
        ),
    ]
