# Generated by Django 4.2.6 on 2023-10-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('przedmioty', '0003_category_parent_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
